// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BasketWithoutRequired basket without required
//
// swagger:model BasketWithoutRequired
type BasketWithoutRequired struct {

	// total price
	TotalPrice float64 `json:"totalPrice,omitempty"`

	// user ID
	UserID int64 `json:"userID,omitempty"`
}

// Validate validates this basket without required
func (m *BasketWithoutRequired) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this basket without required based on context it is used
func (m *BasketWithoutRequired) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BasketWithoutRequired) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BasketWithoutRequired) UnmarshalBinary(b []byte) error {
	var res BasketWithoutRequired
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
