// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CategoryWithoutRequired category without required
//
// swagger:model CategoryWithoutRequired
type CategoryWithoutRequired struct {

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this category without required
func (m *CategoryWithoutRequired) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this category without required based on context it is used
func (m *CategoryWithoutRequired) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CategoryWithoutRequired) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CategoryWithoutRequired) UnmarshalBinary(b []byte) error {
	var res CategoryWithoutRequired
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
